---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apigateway-springboot
  labels:
    app: apigateway-springboot
  namespace: dev
spec:
  serviceName: apigateway-springboot
  replicas: 1
  selector:
    matchLabels:
      app: apigateway-springboot
  template:
    metadata:
      labels:
        app: apigateway-springboot
    spec:
      containers:
      - name: apigateway-springboot
        image: 192.168.20.222:8443/digitalbiohumans/poc/apigateway-springboot:0.0.8-SNAPSHOT
        imagePullPolicy: Always
        env:
          - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
            value: 'true'
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          - name: SPRING_CLOUD_CONFIG_URI
            value: http://food-ordering-springboot-cloud-config:8888
          - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
            value: http://discoveryserver-springboot:8761/eureka
          - name: SPRING_ZIPKIN_BASE_URL
            value: http://zipkin-service-springboot:9411
          - name: SPRING_SLEUTH_ENABLED
            value: 'true'
          - name: SPRING_SLEUTH_SAMPLER_PERCENTAGE
            value: '1.0'
        ports:
        - name: port-tcp
          containerPort: 8082
          protocol: TCP
        - name: port-udp
          containerPort: 8082
          protocol: UDP
        livenessProbe:
          tcpSocket:
            port: 8082
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-springboot
  labels:
    app: apigateway-springboot
  namespace: dev
spec:
  ports:
  - name: gateway-port
    port: 8082
    targetPort: 8082
  clusterIP: 10.152.183.125
  externalIPs:
    - "192.168.20.23"
  selector:
    app: apigateway-springboot
---